# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/inboxWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1053, 582)
        MainWindow.setMinimumSize(QtCore.QSize(520, 0))
        MainWindow.setStyleSheet("QMainWindow{\n"
"    background-color: rgb(11, 1, 55);\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        self.centralwidget.setFont(font)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setMinimumSize(QtCore.QSize(250, 0))
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        self.groupBox.setFont(font)
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.stackedWidget = QtWidgets.QStackedWidget(self.groupBox)
        self.stackedWidget.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        self.stackedWidget.setFont(font)
        self.stackedWidget.setStyleSheet("QStackedWidget{\n"
"    background-color: rrgb(48, 33, 86);\n"
"}")
        self.stackedWidget.setObjectName("stackedWidget")
        self.all_senders_screen = QtWidgets.QWidget()
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        self.all_senders_screen.setFont(font)
        self.all_senders_screen.setObjectName("all_senders_screen")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.all_senders_screen)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.groupBox_2 = QtWidgets.QGroupBox(self.all_senders_screen)
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setPointSize(15)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setAutoFillBackground(False)
        self.groupBox_2.setStyleSheet("\n"
"QGroupBox{\n"
"border: 1px solid grey;\n"
"\n"
"}\n"
"")
        self.groupBox_2.setTitle("")
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.total_senders_label = QtWidgets.QLabel(self.groupBox_2)
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setPointSize(15)
        self.total_senders_label.setFont(font)
        self.total_senders_label.setStyleSheet("color: white;")
        self.total_senders_label.setObjectName("total_senders_label")
        self.verticalLayout_2.addWidget(self.total_senders_label)
        self.total_messages_label = QtWidgets.QLabel(self.groupBox_2)
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setPointSize(15)
        self.total_messages_label.setFont(font)
        self.total_messages_label.setStyleSheet("color: white;")
        self.total_messages_label.setObjectName("total_messages_label")
        self.verticalLayout_2.addWidget(self.total_messages_label)
        self.line_2 = QtWidgets.QFrame(self.groupBox_2)
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        self.line_2.setFont(font)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout_2.addWidget(self.line_2)
        self.set_select_check = QtWidgets.QCheckBox(self.groupBox_2)
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setPointSize(15)
        self.set_select_check.setFont(font)
        self.set_select_check.setStyleSheet("color: white;")
        self.set_select_check.setObjectName("set_select_check")
        self.verticalLayout_2.addWidget(self.set_select_check)
        self.sort_option = QtWidgets.QComboBox(self.groupBox_2)
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setPointSize(15)
        self.sort_option.setFont(font)
        self.sort_option.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.sort_option.setStyleSheet("color: white;")
        self.sort_option.setFrame(True)
        self.sort_option.setObjectName("sort_option")
        self.sort_option.addItem("")
        self.sort_option.addItem("")
        self.sort_option.addItem("")
        self.verticalLayout_2.addWidget(self.sort_option)
        self.line_3 = QtWidgets.QFrame(self.groupBox_2)
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        self.line_3.setFont(font)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.verticalLayout_2.addWidget(self.line_3)
        self.delete_all_button = QtWidgets.QPushButton(self.groupBox_2)
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setPointSize(15)
        self.delete_all_button.setFont(font)
        self.delete_all_button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.delete_all_button.setStyleSheet("QPushButton {\n"
"    width: 80px;\n"
"    height: 25px;\n"
"    color: black;\n"
"    text-align: center;\n"
"    border-radius: 10px;\n"
"    background-color: rgb(255, 101, 118);\n"
"    border: 2px solid black;\n"
"}\n"
"QPushButton::hover {\n"
"    background-color:  rgb(245, 85, 96);\n"
"    border: 0px;\n"
"}\n"
"QPushButton::pressed {\n"
"    \n"
"}\n"
"QPushButton:disabled{\n"
"    background-color:  rgb(123, 124, 125);\n"
"    border: 2px solid black;\n"
"}")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("ui/../icons/delete_btn.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.delete_all_button.setIcon(icon)
        self.delete_all_button.setIconSize(QtCore.QSize(18, 18))
        self.delete_all_button.setObjectName("delete_all_button")
        self.verticalLayout_2.addWidget(self.delete_all_button)
        self.trash_all_button = QtWidgets.QPushButton(self.groupBox_2)
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setPointSize(15)
        self.trash_all_button.setFont(font)
        self.trash_all_button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.trash_all_button.setStyleSheet("QPushButton {\n"
"    width: 80px;\n"
"    height: 25px;\n"
"    color: black;\n"
"    text-align: center;\n"
"    border-radius: 10px;\n"
"    background-color: rgb(255, 101, 118);\n"
"    border: 2px solid black;\n"
"}\n"
"QPushButton::hover {\n"
"    background-color:  rgb(245, 85, 96);\n"
"    border: 0px;\n"
"}\n"
"QPushButton::pressed {\n"
"    \n"
"}\n"
"QPushButton:disabled{\n"
"    background-color:  rgb(123, 124, 125);\n"
"    border: 2px solid black;\n"
"}")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("ui/../icons/trash_bin.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.trash_all_button.setIcon(icon1)
        self.trash_all_button.setIconSize(QtCore.QSize(18, 18))
        self.trash_all_button.setObjectName("trash_all_button")
        self.verticalLayout_2.addWidget(self.trash_all_button)
        self.view_msgs_button = QtWidgets.QPushButton(self.groupBox_2)
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setPointSize(15)
        font.setBold(False)
        self.view_msgs_button.setFont(font)
        self.view_msgs_button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.view_msgs_button.setStyleSheet("QPushButton {\n"
"    width: 80px;\n"
"    height: 25px;\n"
"    color: black;\n"
"    text-align: center;\n"
"    border-radius: 10px;\n"
"    background-color: rgba(30, 165, 255, 186);\n"
"    border: 2px solid black;\n"
"}\n"
"QPushButton::hover {\n"
"    background-color:  rgb(32, 96, 207);\n"
"    border: 0px;\n"
"}\n"
"QPushButton::pressed {\n"
"    \n"
"}\n"
"QPushButton:disabled{\n"
"    background-color:  rgb(123, 124, 125);\n"
"    border: 2px solid black;\n"
"}")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("ui/../icons/view_msg.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.view_msgs_button.setIcon(icon2)
        self.view_msgs_button.setIconSize(QtCore.QSize(17, 16))
        self.view_msgs_button.setObjectName("view_msgs_button")
        self.verticalLayout_2.addWidget(self.view_msgs_button)
        self.unsubscribe_button = QtWidgets.QPushButton(self.groupBox_2)
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setPointSize(15)
        self.unsubscribe_button.setFont(font)
        self.unsubscribe_button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.unsubscribe_button.setStyleSheet("QPushButton {\n"
"    border: 2px solid black;\n"
"    width: 110px;\n"
"    height: 25px;\n"
"    color: black;\n"
"    text-align: center;\n"
"    border-radius: 10px;\n"
"    background-color: rgb(203, 203, 203)\n"
"}\n"
"QPushButton::hover {\n"
"    background-color:  rgb(123, 124, 125);\n"
"    border: 0px;\n"
"}\n"
"QPushButton::pressed {\n"
"    \n"
"}\n"
"QPushButton:disabled{\n"
"    background-color:  rgb(123, 124, 125);\n"
"}")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("ui/../icons/unsubscribe.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.unsubscribe_button.setIcon(icon3)
        self.unsubscribe_button.setObjectName("unsubscribe_button")
        self.verticalLayout_2.addWidget(self.unsubscribe_button)
        self.refresh_button = QtWidgets.QPushButton(self.groupBox_2)
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setPointSize(15)
        self.refresh_button.setFont(font)
        self.refresh_button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.refresh_button.setStyleSheet("QPushButton {\n"
"    border: 2px solid black;\n"
"    width: 110px;\n"
"    height: 25px;\n"
"    color: black;\n"
"    text-align: center;\n"
"    border-radius: 10px;\n"
"    background-color: rgb(157, 198, 150);\n"
"}\n"
"QPushButton::hover {\n"
"    background-color:  rgb(140, 169, 131);\n"
"    border: 0px;\n"
"}\n"
"QPushButton::pressed {\n"
"    \n"
"}\n"
"")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("ui/../icons/refresh_btn.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.refresh_button.setIcon(icon4)
        self.refresh_button.setObjectName("refresh_button")
        self.verticalLayout_2.addWidget(self.refresh_button)
        self.gridLayout_3.addWidget(self.groupBox_2, 0, 1, 2, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem, 2, 1, 1, 1)
        self.sendersList = QtWidgets.QListWidget(self.all_senders_screen)
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setPointSize(15)
        self.sendersList.setFont(font)
        self.sendersList.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.sendersList.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.sendersList.setStyleSheet("QListWidget{\n"
"background-color: transparent;\n"
"}\n"
"QListView::item:selected\n"
"{\n"
"background-color: rgb(173, 173, 173);\n"
"}\n"
"\n"
"QListView::item:hover\n"
"{\n"
"border: 3px solid white;\n"
"}\n"
"QListView::item{\n"
"margin-top: 3px;\n"
"margin-bottom: 2px;\n"
"margin-left: 5px;\n"
"margin-right: 5px;\n"
"spacing: 10px;\n"
"border-radius: 10px;\n"
"color: rgb(9, 1, 63);\n"
"text-align: center;\n"
"background-color: rgb(215, 215, 215);\n"
"height: 45;\n"
"\n"
"}\n"
"")
        self.sendersList.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.sendersList.setFrameShadow(QtWidgets.QFrame.Plain)
        self.sendersList.setLineWidth(1)
        self.sendersList.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.sendersList.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.sendersList.setViewMode(QtWidgets.QListView.ListMode)
        self.sendersList.setObjectName("sendersList")
        self.gridLayout_3.addWidget(self.sendersList, 0, 0, 3, 1)
        self.stackedWidget.addWidget(self.all_senders_screen)
        self.loading_screen = QtWidgets.QWidget()
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        self.loading_screen.setFont(font)
        self.loading_screen.setStyleSheet("color: white;")
        self.loading_screen.setObjectName("loading_screen")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.loading_screen)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.cancelButton = QtWidgets.QPushButton(self.loading_screen)
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setPointSize(16)
        self.cancelButton.setFont(font)
        self.cancelButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.cancelButton.setStyleSheet("QPushButton {\n"
"    width: 90px;\n"
"    height: 40px;\n"
"    color: black;\n"
"    text-align: center;\n"
"    border-radius: 10px;\n"
"    background-color: rgb(255, 101, 118);\n"
"    border: 2px solid black;\n"
"}\n"
"QPushButton::hover {\n"
"    background-color:  rgb(245, 85, 96);\n"
"    border: 0px;\n"
"}\n"
"QPushButton::pressed {\n"
"    \n"
"}\n"
"QPushButton:disabled{\n"
"    background-color:  rgb(123, 124, 125);\n"
"    border: 2px solid black;\n"
"}\n"
"")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("ui/../icons/cancel_btn.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.cancelButton.setIcon(icon5)
        self.cancelButton.setIconSize(QtCore.QSize(18, 18))
        self.cancelButton.setObjectName("cancelButton")
        self.gridLayout_4.addWidget(self.cancelButton, 10, 0, 1, 1, QtCore.Qt.AlignHCenter)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_4.addItem(spacerItem1, 4, 0, 1, 1)
        self.progressBar = QtWidgets.QProgressBar(self.loading_screen)
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setPointSize(16)
        self.progressBar.setFont(font)
        self.progressBar.setStyleSheet("QProgressBar{\n"
"    border-radius: 10px;\n"
"    height: 25px;\n"
"}\n"
"QProgressBar::chunk{\n"
"    border-radius: 10px;\n"
"    background: QLinearGradient( x1: 0, y1: 0,\n"
"                             x2: 1, y2: 0, \n"
"                          stop: 0 #614385, \n"
"                          stop: 1 #516395 );\n"
"    \n"
"}")
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.gridLayout_4.addWidget(self.progressBar, 8, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.loading_screen)
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setPointSize(16)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("")
        self.label_3.setObjectName("label_3")
        self.gridLayout_4.addWidget(self.label_3, 5, 0, 1, 1, QtCore.Qt.AlignHCenter)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_4.addItem(spacerItem2, 9, 0, 1, 1)
        self.count_label = QtWidgets.QLabel(self.loading_screen)
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setPointSize(15)
        self.count_label.setFont(font)
        self.count_label.setStyleSheet("padding: 10px;\n"
"padding-bottom: 20px;")
        self.count_label.setObjectName("count_label")
        self.gridLayout_4.addWidget(self.count_label, 7, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.stackedWidget.addWidget(self.loading_screen)
        self.default_page = QtWidgets.QWidget()
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        self.default_page.setFont(font)
        self.default_page.setObjectName("default_page")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.default_page)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_4 = QtWidgets.QLabel(self.default_page)
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setPointSize(26)
        font.setBold(False)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("color: white;")
        self.label_4.setObjectName("label_4")
        self.verticalLayout.addWidget(self.label_4, 0, QtCore.Qt.AlignHCenter)
        self.stackedWidget.addWidget(self.default_page)
        self.subjects_page = QtWidgets.QWidget()
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        self.subjects_page.setFont(font)
        self.subjects_page.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.subjects_page.setObjectName("subjects_page")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.subjects_page)
        self.gridLayout_5.setObjectName("gridLayout_5")
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_5.addItem(spacerItem3, 3, 6, 1, 1)
        self.groupBox_3 = QtWidgets.QGroupBox(self.subjects_page)
        self.groupBox_3.setMinimumSize(QtCore.QSize(0, 250))
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setPointSize(15)
        self.groupBox_3.setFont(font)
        self.groupBox_3.setStyleSheet("\n"
"QGroupBox{\n"
"border: 1px solid grey;\n"
"}")
        self.groupBox_3.setTitle("")
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.select_msgs_chkbox = QtWidgets.QCheckBox(self.groupBox_3)
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setPointSize(15)
        self.select_msgs_chkbox.setFont(font)
        self.select_msgs_chkbox.setStyleSheet("color: white;")
        self.select_msgs_chkbox.setObjectName("select_msgs_chkbox")
        self.verticalLayout_3.addWidget(self.select_msgs_chkbox)
        self.msg_sort_option = QtWidgets.QComboBox(self.groupBox_3)
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setPointSize(15)
        self.msg_sort_option.setFont(font)
        self.msg_sort_option.setStyleSheet("color: white;")
        self.msg_sort_option.setObjectName("msg_sort_option")
        self.msg_sort_option.addItem("")
        self.msg_sort_option.addItem("")
        self.msg_sort_option.addItem("")
        self.verticalLayout_3.addWidget(self.msg_sort_option)
        self.delete_message_button = QtWidgets.QPushButton(self.groupBox_3)
        self.delete_message_button.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setPointSize(15)
        self.delete_message_button.setFont(font)
        self.delete_message_button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.delete_message_button.setStyleSheet("QPushButton {\n"
"    width: 80px;\n"
"    height: 25px;\n"
"    color: black;\n"
"    text-align: center;\n"
"    border-radius: 10px;\n"
"    background-color: rgb(255, 101, 118);\n"
"    border: 2px solid black;\n"
"}\n"
"QPushButton::hover {\n"
"    background-color:  rgb(245, 85, 96);\n"
"    border: 0px;\n"
"}\n"
"QPushButton::pressed {\n"
"    \n"
"}\n"
"QPushButton:disabled{\n"
"    background-color:  rgb(123, 124, 125);\n"
"    border: 2px solid black;\n"
"}")
        self.delete_message_button.setIcon(icon)
        self.delete_message_button.setIconSize(QtCore.QSize(18, 18))
        self.delete_message_button.setObjectName("delete_message_button")
        self.verticalLayout_3.addWidget(self.delete_message_button)
        self.trash_message_button = QtWidgets.QPushButton(self.groupBox_3)
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setPointSize(15)
        self.trash_message_button.setFont(font)
        self.trash_message_button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.trash_message_button.setStyleSheet("QPushButton {\n"
"    width: 80px;\n"
"    height: 25px;\n"
"    color: black;\n"
"    text-align: center;\n"
"    border-radius: 10px;\n"
"    background-color: rgb(255, 101, 118);\n"
"    border: 2px solid black;\n"
"}\n"
"QPushButton::hover {\n"
"    background-color:  rgb(245, 85, 96);\n"
"    border: 0px;\n"
"}\n"
"QPushButton::pressed {\n"
"    \n"
"}\n"
"QPushButton:disabled{\n"
"    background-color:  rgb(123, 124, 125);\n"
"    border: 2px solid black;\n"
"}")
        self.trash_message_button.setIcon(icon1)
        self.trash_message_button.setIconSize(QtCore.QSize(18, 18))
        self.trash_message_button.setObjectName("trash_message_button")
        self.verticalLayout_3.addWidget(self.trash_message_button)
        self.open_browser_bttn = QtWidgets.QPushButton(self.groupBox_3)
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setPointSize(15)
        self.open_browser_bttn.setFont(font)
        self.open_browser_bttn.setStyleSheet("QPushButton {\n"
"    width: 80px;\n"
"    height: 25px;\n"
"    color: black;\n"
"    text-align: center;\n"
"    border-radius: 10px;\n"
"    background-color: rgba(30, 165, 255, 186);\n"
"    border: 2px solid black;\n"
"}\n"
"QPushButton::hover {\n"
"    background-color:  rgb(32, 96, 207);\n"
"    border: 0px;\n"
"}\n"
"QPushButton::pressed {\n"
"    \n"
"}\n"
"QPushButton:disabled{\n"
"    background-color:  rgb(123, 124, 125);\n"
"    border: 2px solid black;\n"
"}")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("ui/../icons/open_web.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.open_browser_bttn.setIcon(icon6)
        self.open_browser_bttn.setIconSize(QtCore.QSize(18, 18))
        self.open_browser_bttn.setObjectName("open_browser_bttn")
        self.verticalLayout_3.addWidget(self.open_browser_bttn)
        self.line_4 = QtWidgets.QFrame(self.groupBox_3)
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        self.line_4.setFont(font)
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.verticalLayout_3.addWidget(self.line_4)
        self.backButton = QtWidgets.QPushButton(self.groupBox_3)
        self.backButton.setMinimumSize(QtCore.QSize(90, 0))
        self.backButton.setMaximumSize(QtCore.QSize(90, 16777215))
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.backButton.setFont(font)
        self.backButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.backButton.setStyleSheet("QPushButton {\n"
"    width: 30px;\n"
"    height: 20px;\n"
"    color: white;\n"
"    text-align: center;\n"
"    border-radius: 0px;\n"
"    background-color: transparent;\n"
"}\n"
"QPushButton::hover {\n"
"    text-decoration: underline;\n"
"}\n"
"QPushButton::pressed {\n"
"    \n"
"}\n"
"")
        icon = QtGui.QIcon.fromTheme("QStyle::SP_ArrowBack")
        self.backButton.setIcon(icon)
        self.backButton.setObjectName("backButton")
        self.verticalLayout_3.addWidget(self.backButton, 0, QtCore.Qt.AlignHCenter)
        self.gridLayout_5.addWidget(self.groupBox_3, 1, 6, 2, 1)
        self.subjectsList = QtWidgets.QListWidget(self.subjects_page)
        self.subjectsList.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setPointSize(15)
        self.subjectsList.setFont(font)
        self.subjectsList.setStyleSheet("QListWidget{\n"
"background-color: transparent;\n"
"}\n"
"QListView::item:selected\n"
"{\n"
"background-color: rgb(173, 173, 173);\n"
"}\n"
"\n"
"QListView::item:hover\n"
"{\n"
"border: 3px solid white;\n"
"}\n"
"QListView::item{\n"
"margin-top: 3px;\n"
"margin-bottom: 2px;\n"
"margin-left: 5px;\n"
"margin-right: 5px;\n"
"spacing: 10px;\n"
"border-radius: 10px;\n"
"color: rgb(9, 1, 63);\n"
"text-align: center;\n"
"background-color: rgb(215, 215, 215);\n"
"height: 45;\n"
"\n"
"}\n"
"")
        self.subjectsList.setObjectName("subjectsList")
        self.gridLayout_5.addWidget(self.subjectsList, 1, 0, 4, 6)
        self.stackedWidget.addWidget(self.subjects_page)
        self.gridLayout_2.addWidget(self.stackedWidget, 1, 1, 3, 3)
        self.gridLayout.addWidget(self.groupBox, 1, 1, 6, 1)
        self.addAcctButton = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setPointSize(15)
        self.addAcctButton.setFont(font)
        self.addAcctButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.addAcctButton.setStyleSheet("QPushButton {\n"
"    border: 2px solid black;\n"
"    width: 110px;\n"
"    height: 25px;\n"
"    color: black;\n"
"    text-align: center;\n"
"    border-radius: 10px;\n"
"    background-color: rgb(203, 203, 203)\n"
"}\n"
"QPushButton::hover {\n"
"    background-color:  rgb(123, 124, 125);\n"
"    border: 0px;\n"
"}\n"
"QPushButton::pressed {\n"
"    \n"
"}\n"
"QPushButton:disabled{\n"
"    background-color:  rgb(123, 124, 125);\n"
"}\n"
"\n"
"\n"
"\n"
"")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("ui/../icons/add_btn.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.addAcctButton.setIcon(icon7)
        self.addAcctButton.setIconSize(QtCore.QSize(22, 22))
        self.addAcctButton.setObjectName("addAcctButton")
        self.gridLayout.addWidget(self.addAcctButton, 3, 0, 2, 1)
        self.line = QtWidgets.QFrame(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        self.line.setFont(font)
        self.line.setStyleSheet("color: white;")
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout.addWidget(self.line, 2, 0, 1, 1)
        self.accountsList = QtWidgets.QListWidget(self.centralwidget)
        self.accountsList.setMinimumSize(QtCore.QSize(132, 0))
        self.accountsList.setMaximumSize(QtCore.QSize(140, 16777215))
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setPointSize(13)
        font.setBold(False)
        self.accountsList.setFont(font)
        self.accountsList.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.accountsList.setStyleSheet("QListView{\n"
"min-width:130px;\n"
"background-color: rgb(45, 34, 78);\n"
"}\n"
"QListView::item:selected\n"
"{\n"
"background-color: rgb(173, 173, 173);\n"
"border: 3px solid white;\n"
"}\n"
"\n"
"QListView::item:hover\n"
"{\n"
"border: 3px solid white;\n"
"}\n"
"QListView::item{\n"
"margin-top: 7px;\n"
"margin-bottom: 2px;\n"
"margin-left: 5px;\n"
"margin-right: 5px;\n"
"spacing: 10px;\n"
"border-radius: 10px;\n"
"color: rgb(9, 1, 63);\n"
"text-align: center;\n"
"background-color: rgb(215, 215, 215);\n"
"height: 30;\n"
"\n"
"}\n"
"")
        self.accountsList.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.accountsList.setTextElideMode(QtCore.Qt.ElideMiddle)
        self.accountsList.setViewMode(QtWidgets.QListView.ListMode)
        self.accountsList.setObjectName("accountsList")
        self.gridLayout.addWidget(self.accountsList, 1, 0, 1, 1)
        self.action_label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setPointSize(19)
        font.setBold(True)
        self.action_label.setFont(font)
        self.action_label.setStyleSheet("color: white;")
        self.action_label.setObjectName("action_label")
        self.gridLayout.addWidget(self.action_label, 0, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setPointSize(15)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: white;")
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Mail"))
        self.total_senders_label.setText(_translate("MainWindow", "Senders: "))
        self.total_messages_label.setText(_translate("MainWindow", "Messages: "))
        self.set_select_check.setText(_translate("MainWindow", "Select"))
        self.sort_option.setCurrentText(_translate("MainWindow", "Newest"))
        self.sort_option.setItemText(0, _translate("MainWindow", "Newest"))
        self.sort_option.setItemText(1, _translate("MainWindow", "Oldest"))
        self.sort_option.setItemText(2, _translate("MainWindow", "Alphabetical"))
        self.delete_all_button.setText(_translate("MainWindow", "Delete All"))
        self.trash_all_button.setText(_translate("MainWindow", "Trash All"))
        self.view_msgs_button.setText(_translate("MainWindow", "View"))
        self.unsubscribe_button.setText(_translate("MainWindow", "Unsubscribe"))
        self.refresh_button.setText(_translate("MainWindow", "Refresh List"))
        self.cancelButton.setText(_translate("MainWindow", "Cancel"))
        self.label_3.setText(_translate("MainWindow", "Please Do Not Close The Application"))
        self.count_label.setText(_translate("MainWindow", "Waiting..."))
        self.label_4.setText(_translate("MainWindow", "Select or Add Account to Continue"))
        self.select_msgs_chkbox.setText(_translate("MainWindow", "Select"))
        self.msg_sort_option.setItemText(0, _translate("MainWindow", "Newest"))
        self.msg_sort_option.setItemText(1, _translate("MainWindow", "Oldest"))
        self.msg_sort_option.setItemText(2, _translate("MainWindow", "Alphabetical"))
        self.delete_message_button.setText(_translate("MainWindow", "Delete"))
        self.trash_message_button.setText(_translate("MainWindow", "Trash"))
        self.open_browser_bttn.setText(_translate("MainWindow", "Open Browser"))
        self.backButton.setText(_translate("MainWindow", "Back"))
        self.addAcctButton.setText(_translate("MainWindow", "Add Account"))
        self.action_label.setText(_translate("MainWindow", "Messages"))
        self.label_2.setText(_translate("MainWindow", "Accounts"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
