# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'infoRequestWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_InfoRequestWindow(object):
    def setupUi(self, InfoRequestWindow):
        InfoRequestWindow.setObjectName("InfoRequestWindow")
        InfoRequestWindow.resize(247, 143)
        self.centralwidget = QtWidgets.QWidget(InfoRequestWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.gmail_username = QtWidgets.QLineEdit(self.centralwidget)
        self.gmail_username.setStyleSheet("height: 20999px;")
        self.gmail_username.setText("")
        self.gmail_username.setObjectName("gmail_username")
        self.gridLayout.addWidget(self.gmail_username, 0, 0, 1, 1)
        self.submit_button = QtWidgets.QPushButton(self.centralwidget)
        self.submit_button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.submit_button.setStyleSheet("\n"
"QPushButton {\n"
"    color: black;\n"
"    text-align: center;\n"
"    border-radius: 4px;\n"
"    height: 30px;\n"
"    width: 4px;\n"
"    background-color: rgb(85, 199, 255);\n"
"}\n"
"QPushButton::hover {\n"
"    background-color: rgb(179, 239, 255)\n"
"}\n"
"QPushButton::pressed {\n"
"    \n"
"}\n"
"")
        self.submit_button.setObjectName("submit_button")
        self.gridLayout.addWidget(self.submit_button, 1, 0, 1, 1)
        InfoRequestWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(InfoRequestWindow)
        QtCore.QMetaObject.connectSlotsByName(InfoRequestWindow)

    def retranslateUi(self, InfoRequestWindow):
        _translate = QtCore.QCoreApplication.translate
        InfoRequestWindow.setWindowTitle(_translate("InfoRequestWindow", "MainWindow"))
        self.gmail_username.setPlaceholderText(_translate("InfoRequestWindow", "Gmail USERNAME"))
        self.submit_button.setText(_translate("InfoRequestWindow", "Submit"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    InfoRequestWindow = QtWidgets.QMainWindow()
    ui = Ui_InfoRequestWindow()
    ui.setupUi(InfoRequestWindow)
    InfoRequestWindow.show()
    sys.exit(app.exec_())
